name: Bundle

on:
  # Run when a release is published
  release:
    types:
      - published

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: Install Roc
        uses: roc-lang/setup-roc@cbe782d6f165b89c87d99f50a59ac4f5f73b4427 # ratchet:roc-lang/setup-roc@v0.3.0
        with:
          version: nightly-new-compiler
      - name: Bundle and release the library
        uses: hasnep/bundle-roc-library@f9e57fba045b0f90a73fd3b32ea2bb1293edb961 # ratchet:hasnep/bundle-roc-library@v0.2.1
        with:
          library: src/main.roc
          token: ${{ github.token }}
