name: Run Pre-commit

on:
  # Run on all PRs
  pull_request:
  # Run when a PR is merged into main
  push:
    branches:
      - main

jobs:
  run-pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # ratchet:nixbuild/nix-quick-install-action@v35
      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # ratchet:nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: Use Nix dev shell for subsequent steps
        uses: rrbutani/use-nix-shell-action@59a52b2b9bbfe3cc0e7deb8f9059abe37a439edf # ratchet:rrbutani/use-nix-shell-action@v1.1.0
        with:
          extraNixOptions: --accept-flake-config
      - name: Run Pre-commit
        run: pre-commit run --all-files
        env:
          # Prevent this action failing when running on the main branch
          SKIP: no-commit-to-branch
