name: Test

on:
  # Run on all PRs
  pull_request:
    paths-ignore:
      - "**.md"
  # Run when a PR is merged into main
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2
      - name: Install Roc
        uses: hasnep/setup-roc@f1f8d74d6b48104216ebb0556043f44a8729889c # ratchet:hasnep/setup-roc@v0.2.0
        with:
          roc-version: nightly
      - name: Test the library
        run: roc test src/main.roc
